config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "restaurants#index"

  resources :restaurants, shallow: true do
  resources :reviews do
    resources :endorsements
  end
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

has_attached_file :image, 
                  :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
                  :default_url => "/images/:style/missing.png"

validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

has_many :reviews,
       -> { extending WithUserAssociationExtension }, 
      dependent: :destroy
belongs_to :user
 validates :name, length: {minimum: 3}, uniqueness: true

  
  def build_review(attributes={}, user)
  attributes[:user] ||= user 
  reviews.build(attributes)
  end

  def average_rating
  return 'N/A' if reviews.none?
  reviews.inject(0) {|memo, review| memo + review.rating} / reviews.size
	end


end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: {scope: :restaurant, message:'user has already reviewed the restaurant'}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :restaurants 
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  
  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]

    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.create(comment_params)
    redirect_to restaurant_path(@restaurant) 
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :rating)
  end
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
end

app/controllers/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

@user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication 
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end



end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :expect => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :image)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.build_review review_params,current_user
    if @review.save
      redirect_to restaurants_path
    else
    if @review.errors[:user]
      redirect_to restaurants_path, alert:"you have already reviewed this restaurant"
    else
      render :new  
    end
  end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = 'review deleted successfully'
    redirect_to '/restaurants'
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

 def facebook 
  @user = User.from_omniauth(request.env["omniauth.auth"])
  if @user.persisted?
    sign_in_and_redirect @user, :event => :authentication 
    set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
  else
    session["devise.facebook_data"] = request.env["omniauth.auth"]
    redirect_to new_user_registration_url
  end
end

def failure
  redirect_to root_path
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    "★" * rating.round + "☆" * remainder
  end
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>

  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
  <% end %>
<%= notice %> <%= alert %> 
<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2> <h2>Average rating: <%= star_rating(restaurant.average_rating) %></h2>
    <%= image_tag restaurant.image.url(:thumb) %>
    <% if current_user == restaurant.user %>
    <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %> 
    <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
    <% end %>
    <% unless current_user.has_reviewed? restaurant %>
    <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
    <% end %>


    <h3>Reviews for <%= restaurant.name %></h3>

    <% if restaurant.reviews.any? %>
      <ul>
        <% restaurant.reviews.each do |review| %>
          <li>
            <%= review.thoughts %>, <strong><%= review.rating %></strong>/5
            <% if review.user == current_user %>
            <%= link_to "Delete #{review.restaurant.name} Review", review_path(review), method: :delete %>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No reviews.</p>
    <% end %>
  <% end %>
<% else %>
  <h1>No restaurants yet!</h1>
<% end %>

<a href='restaurants/new'>Add a restaurant</a>

app/views/restaurants/new.html.erb
<doctype html>
<html>
<head>
</head>
<body>
<% if @restaurant.errors.any? %>
<style>

input[type="text"], textarea {
  background-color : red;
}
</style>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

<%= form_for @restaurant, html: {multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>
</body>
</html>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
  <% if @restaurant.reviews.any? %>
    <p>Average rating: <%= @restaurant.average_rating %></p>
  <% end %>
<p><%= @restaurant.description %></p>

<h3>Reviews for <%= @restaurant.name %>
</h3>

<% if @restaurant.reviews.any? %>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <%= review.thoughts %>, <strong><%= review.rating %></strong>/5
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No reviews.</p>
<% end %>

app/views/reviews/new.html.erb
<% if @review.errors.any? %>
	<h2> <%= pluralize(@review.errors.count, "error") %> not allowed to be saved: </h2>
	<ul> 
			<% @review.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
			<% end %>
	</ul>		 
	<% end %> 

<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (0..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>